export const showcase = [
  {
    name: 'Disparity Dashboard',
    slug: 'openai',
    thumbnail: require('@/img/showcase/thumbnails/openai.com.png').default,
    video: require('@/videos/showcase/openai.com.mp4').default,
    description: 'Lancet DH (2023)',
  },
  {
    name: 'Diversity Factor',
    slug: 'lemon-squeezy',
    thumbnail: require('@/img/showcase/thumbnails/app.lemonsqueezy.com.png').default,
    video: require('@/videos/showcase/app.lemonsqueezy.com.mp4').default,
    description: 'PLOS DH (2023)',
  },
  {
    name: 'Digital Determinants of Health',
    slug: 'shopify',
    thumbnail: require('@/img/showcase/thumbnails/shopify.com.png').default,
    video: require('@/videos/showcase/shopify.com.mp4').default,
    description: 'Nature Reviews Nephrology (2023)',
  },
  {
    name: 'Digital Divide',
    slug: 'wealthfront',
    thumbnail: require('@/img/showcase/thumbnails/wealthfront.com.png').default,
    video: require('@/videos/showcase/wealthfront.com.mp4').default,
    description: 'MedRxiv (2023)',
  },
  {
    name: 'CMS Reform Response',
    slug: 'netflix',
    thumbnail: require('@/img/showcase/thumbnails/top10.netflix.com.png').default,
    video: require('@/videos/showcase/top10.netflix.com.mp4').default,
    description: 'Health Affairs Forefront (2023)',
  },
  {
    name: 'Bias in Critical Care Devices',
    slug: 'loom',
    thumbnail: require('@/img/showcase/thumbnails/loom.com.png').default,
    video: require('@/videos/showcase/loom.com.mp4').default,
    description: 'Critical Care Clinics (2023)',
  },
  {
    name: 'AI in Mechanical Ventilation',
    slug: 'the-verge',
    thumbnail: require('@/img/showcase/thumbnails/theverge.com.png').default,
    video: require('@/videos/showcase/theverge.com.mp4').default,
    description: 'BJA (2022)',
  },
  {
    name: 'Lobar Gas Exchange',
    slug: 'laracon',
    thumbnail: require('@/img/showcase/thumbnails/laracon.net.png').default,
    video: require('@/videos/showcase/laracon.net.mp4').default,
    description: 'BJA (2021)',
  },
  {
    name: 'AI Publication Dashboard',
    slug: 'turbo',
    thumbnail: require('@/img/showcase/thumbnails/turbo.build.png').default,
    video: require('@/videos/showcase/turbo.build.mp4').default,
    description: 'Lancet DH (2022)',
  },
  {
    name: 'Equity and Health Innovation',
    slug: 'candycode',
    thumbnail: require('@/img/showcase/thumbnails/candycode.com.png').default,
    video: require('@/videos/showcase/candycode.com.mp4').default,
    description: 'PLOS DH (2023)',
  },
  {
    name: 'Ventilators for LMICs',
    slug: 'column',
    thumbnail: require('@/img/showcase/thumbnails/column.com.png').default,
    video: require('@/videos/showcase/column.com.mp4').default,
    description: 'BJA (2022)',
  },
  {
    name: 'Avoiding Open Data In Appearence Only',
    slug: 'wander',
    thumbnail: require('@/img/showcase/thumbnails/wander.com.png').default,
    video: require('@/videos/showcase/wander.com.mp4').default,
    description: 'BMJ HCI (2023',
  },
  {
    name: 'Pulse Oximeter Bias Corrections',
    slug: 'nytimes',
    thumbnail: require('@/img/showcase/thumbnails/nytimes.com.png').default,
    video: require('@/videos/showcase/nytimes.com.mp4').default,
    description: 'IEEE (2023)',
  },
  {
    name: 'Medical Knowledge Graphs',
    slug: 'github',
    thumbnail: require('@/img/showcase/thumbnails/githubnext.com.png').default,
    video: require('@/videos/showcase/githubnext.com.mp4').default,
    description: 'medRxiv (2023)',
  },
]
