export const showcase = [
  {
    name: 'Disparity Dashboard',
    slug: 'openai',
    thumbnail: require('@/img/showcase/thumbnails/openai.com.png').default,
    video: require('@/videos/showcase/openai.com.mp4').default,
    description: 'Lancet DH (2023)',
  },
  {
    name: 'Diversity Factor',
    slug: 'lemon-squeezy',
    thumbnail: require('@/img/showcase/thumbnails/div_fact.png').default,
    video: require('@/videos/showcase/div_factor.mp4').default,
    description: 'PLOS DH (2023)',
  },
  {
    name: 'Digital Determinants of Health',
    slug: 'shopify',
    thumbnail: require('@/img/showcase/thumbnails/ddoh.png').default,
    video: require('@/videos/showcase/ddoh.mp4').default,
    description: 'Nature Reviews Nephrology (2023)',
  },
  {
    name: 'Digital Divide',
    slug: 'wealthfront',
    thumbnail: require('@/img/showcase/thumbnails/dig_ineq.png').default,
    video: require('@/videos/showcase/dig_ineq.mp4').default,
    description: 'MedRxiv (2023)',
  },
  {
    name: 'CMS Reform Response',
    slug: 'netflix',
    thumbnail: require('@/img/showcase/thumbnails/top10.netflix.com.png').default,
    video: require('@/videos/showcase/top10.netflix.com.mp4').default,
    description: 'Health Affairs Forefront (2023)',
  },
  {
    name: 'Bias in Critical Care Devices',
    slug: 'loom',
    thumbnail: require('@/img/showcase/thumbnails/crit_bias.png').default,
    video: require('@/videos/showcase/crit_bias.mp4').default,
    description: 'Critical Care Clinics (2023)',
  },
  {
    name: 'AI in Mechanical Ventilation',
    slug: 'the-verge',
    thumbnail: require('@/img/showcase/thumbnails/sr_ai_vent.png').default,
    video: require('@/videos/showcase/sr_ai_vent.mp4').default,
    description: 'BJA (2022)',
  },
  {
    name: 'Lobar Gas Exchange',
    slug: 'laracon',
    thumbnail: require('@/img/showcase/thumbnails/lob_gas.png').default,
    video: require('@/videos/showcase/lobar_gas.mp4').default,
    description: 'BJA (2021)',
  },
  {
    name: 'AI Publication Dashboard',
    slug: 'turbo',
    thumbnail: require('@/img/showcase/thumbnails/ai_dash.png').default,
    video: require('@/videos/showcase/ai_dash.mp4').default,
    description: 'Lancet DH (2022)',
  },
  {
    name: 'Equity and Health Innovation',
    slug: 'candycode',
    thumbnail: require('@/img/showcase/thumbnails/equity_funda.png').default,
    video: require('@/videos/showcase/equity_fundamental.mp4').default,
    description: 'PLOS DH (2023)',
  },
  {
    name: 'Ventilators for LMICs',
    slug: 'column',
    thumbnail: require('@/img/showcase/thumbnails/lmic_vent.png').default,
    video: require('@/videos/showcase/lmic_vent.mp4').default,
    description: 'BJA (2022)',
  },
  {
    name: 'Avoiding Open Data In Appearence Only',
    slug: 'wander',
    thumbnail: require('@/img/showcase/thumbnails/odiao.png').default,
    video: require('@/videos/showcase/odiao.mp4').default,
    description: 'BMJ HCI (2023',
  },
  {
    name: 'Pulse Oximeter Bias Corrections',
    slug: 'nytimes',
    thumbnail: require('@/img/showcase/thumbnails/shine_light.png').default,
    video: require('@/videos/showcase/pulse_light.mp4').default,
    description: 'IEEE (2023)',
  },
  {
    name: 'Medical Knowledge Graphs',
    slug: 'github',
    thumbnail: require('@/img/showcase/thumbnails/oligarchy.png').default,
    video: require('@/videos/showcase/oligarchy.mp4').default,
    description: 'medRxiv (2023)',
  },
]
